Include bundled glew headers when GLEW_STATIC
In file included from src/camotics/contour/TriangleSurface.cpp:30:0:
src/camotics/view/GL.h:24:38: fatal error: GL/glew.h: No such file or directory
 #include <GL/glew.h> // Must be first
                                      ^
compilation terminated.
scons: *** [build/camotics/contour/TriangleSurface.o] Error 1
scons: building terminated because of errors.